- name: copy init script
  copy:
    src=bild-ord.sh
    dest=/etc/init.d/bild-ord
    owner=root
    group=root
    mode=0755

- name: copy app jar
  copy:
    src=../../target/uberjar/bild-ord-{{ app_version }}-standalone.jar
    dest=/opt/bild-ord/bild-ord-{{ app_version }}.jar
    owner=root
    group=root
    mode=0644
  register: upload_app_jar

- name: link to current app release 
  file:
    dest=/opt/bild-ord/bild-ord-current.jar
    src=/opt/bild-ord/bild-ord-{{ app_version }}.jar
    owner=root
    group=root
    state=link
    force=yes

- name: remove old deploys (keeping the two latest)
  shell: "ls -tr /opt/bild-ord*.jar | head -n -2 | xargs rm -Rf"

-  command: /bin/true
   notify: 
     - restart app server
