- apt_repository: repo='ppa:webupd8team/java'

- name: Accept Oracle license
  debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value=true vtype=select

- apt: update_cache=yes

- locale_gen: name=sv_FI.UTF-8 state=present

- name: Install Java 8
  apt: name=oracle-java8-installer state=latest

- name: Set Java environment variables
  apt: name=oracle-java8-set-default state=latest

- name: Create app directory
  file: path=/opt/bild-ord state=directory

