- hosts: 127.0.0.1
  connection: local
  sudo: yes
  tasks:
    - include: tasks/main.yml
    - include: tasks/lein.yml
    - include: tasks/sqlite.yml
    - include: tasks/app.yml
  vars_files: 
    - vars.yml
  vars:
    # app_version is normally given as an extra var on the command line
    - app_version: 0.1.0-SNAPSHOT
  roles:
    - role: franklinkim.environment
      environment_config:
        PORT: 8080
    - role: jdauphant.nginx
      nginx_http_params:
        - access_log "/var/log/nginx/access.log"
      nginx_sites:
        default:
          - listen 80
          - server_name _
          - location / {
              proxy_pass       http://localhost:8080;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header Host $http_host; 
            }
  handlers:
    - name: restart app server
      service: name=bild-ord state=restarted


